### ISSUE TITLE
looking at sky sources in the 1.2p processing 210918:coadd-all2

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/DC2-production#304] opened 2018-12-03 13:08 UTC
I am trying to capture here some discussion/investigation with @RobertLuptonTheGood that tries to understand why in some patches there are too many sources detected in the coadd. 
The `stack` looks for blank regions in the coadded calexps, and adds spurious sources to handle some sky noise information and possibly threshold rescaling if needs be. These sky sources can be selected using `is_sky = srcs.get('merge_peak_sky')` where `srcs` is the `deepCoadd_meas` catalogue for a given tract/patch/filter selection. 
This can be useful to try to understand whether the threshold to source detection is adequate, and whether this is the problem in the fact that some patches have much too many sources in them. 
The diagnostics proposed by @RobertLuptonTheGood  is to look at the flux chi distribution for these spurious sources, namely psfFlux/psfFluxSigma.
If I plot this distribution for all the sky sources in 1.2p, I get : 
![image](https://user-images.githubusercontent.com/586081/49377464-894c1b00-f70a-11e8-9b9e-f9673127eb30.png)
which shows a very pathological high ratio tail, stemming from essentially 4 tracts : 5065, 5063, 4848, and 4849. Not surprisingly, these include the tracts that were hardest to process.
If I remove these four tracts alltogether, I get the following historgram : 
![image](https://user-images.githubusercontent.com/586081/49378675-7850d900-f70d-11e8-906d-2e9842439975.png)
where the curve is a gaussian of mean and sigma the distribution mean and std, respectively (std=1.45). The high tail is still there, and the behavior at negative flux seems compatible with the gaussian shape (no fit here, just a quick visual adjustment). @RobertLuptonTheGood  pointed out that the value 1.45 is too large and shows that the threshold is too low, even for the sane tracts.

**Comment by johannct** [comment] 2018-12-03 14:16
One of the worst tract/patch in terms of the high tail contribution is 5065 0,2 i. Here is the calexp coadd with the sky sources, provided by @boutigny : 
https://files.slack.com/files-pri/T06D204F2-FEH7Z1T7T/image.png
It does look fine : enough sky sources in the right places (blank sky region)

**Comment by boutigny** [comment] 2018-12-03 14:48
On the same tract, patch (5065 0,2 i) here is the position of the sources with `'merge_peak_i' == True` and `detect_isPrimary == True`. There is not a single source with `detect_isPrimary == True` in the left part of the image. 
I don't know if it is related but one can also notice the  set of negative pixels surrounding a spike on the bright star on the left.
![screenshot at 2018-12-03 15-38-59](https://user-images.githubusercontent.com/5713323/49380798-c5837980-f712-11e8-9b71-72498d835fd3.png)

**Comment by johannct** [comment] 2018-12-03 15:13
ok so, in order : 
- sources with `primary=False` in the patch border : is this expected because this is a region of patch overlaps?
- does the deblender proceeds with sources in increasing order of RA?
- why aren't there any primary sources for all the secondary sources on the left?
- why is the psf-like source at the top middle right not detected?

**Comment by TallJimbo** [comment] 2018-12-03 15:47
The behavior of `isPrimary` here is indeed totally expected.  There are fewer with `isPrimary=True` on the border because of patch overlaps, and a jump from left-to-right because of tract overlaps.

The order of source IDs is set by something like the following:
 - parent sources are added just after detection, and follow the direction the detection algorithm takes (chunks of rows, I think).
 - child sources are added in the deblender, one parent at a time.
But nothing should depend on that ordering, except perhaps that all of the parents come before any of the children.

**Comment by johannct** [comment] 2018-12-03 15:54
So that leaves : 
- the variance size and tail in the sky source flux/fluxerr distribution
- the case of the source without detection

**Comment by johannct** [comment] 2018-12-05 08:17
--longlog pushed to IPP branch `dc2/run1.2-v3`. I can close this issue as a `won't fix` once the people above mark sign it off, or else should we try to hammer it down?

**Comment by heather999** [comment] 2018-12-05 17:04
Just checking in after reviewing our notes from the DM-DC2 mtg on Monday.  I want to confirm what warning @TallJimbo referred to on Slack and at the meeting ("Have you ruled out that warning about not having enough sky object measurements as the cause?"), is that the same as `Insufficient good flux measurements` @johannct mentioned above? [https://lsstc.slack.com/archives/C978LTJGN/p1543852251057700](https://lsstc.slack.com/archives/C978LTJGN/p1543852251057700)

@TallJimbo also mentioned trying to debug the dynamic detection task using a patch without the "not enough sky objects" warning and looking at the logs to see how the threshold is changed.. then rerunning through detect coadd sources task without dynamic detection, one band at a time, and explicitly setting the threshold to 5 sigma of the values seen in the log.  Is that still useful and is someone planning to do that?

**Comment by johannct** [comment] 2018-12-06 06:17
> Just checking in after reviewing our notes from the DM-DC2 mtg on Monday. I want to confirm what warning @TallJimbo referred to on Slack and at the meeting ("Have you ruled out that warning about not having enough sky object measurements as the cause?"), is that the same as `Insufficient good flux measurements` @johannct mentioned above? https://lsstc.slack.com/archives/C978LTJGN/p1543852251057700
> 
> @TallJimbo also mentioned trying to debug the dynamic detection task using a patch without the "not enough sky objects" warning and looking at the logs to see how the threshold is changed.. then rerunning through detect coadd sources task without dynamic detection, one band at a time, and explicitly setting the threshold to 5 sigma of the values seen in the log. Is that still useful and is someone planning to do that?

yes to all, and the work to be done is captured in a jira now, see my summary above.

**Comment by katrinheitmann** [comment] 2019-12-29 00:03
@johannct Hi Johann, This issue is dormant for a year or so. Since it concerns Run 1.2p, I wonder if we can close it? Thanks!

**Comment by johannct** [comment] 2019-12-29 01:28
@katrinheitmann I should give a look  to the sky sources with the current 2.2 validation run actually, before closing it.

**Closed** 2019-12-29 17:48 UTC
Labels: Run1.2, validation
