### ISSUE TITLE
Meet with Grid folks to discuss Run2.2i sims including checkpoint files

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#371] opened 2019-09-20 03:03 UTC
As discussed this week at the DESC DM meeting, we should have a Zoom meeting that includes George B, James P, Fabio, Dominique B, Katrin, Antonio, etc. There we will discuss the simulation processing, including the creation and storage of checkpoint files.

**Comment by boutigny** [comment] 2019-10-08 17:17
Here is my summary of today's meeting, please feel free to correct it:

Present: Fabio, George, James, Jim, Heather, Katrin, Antonio and Dominique

- The time scale to resume DC2 simulation is ~2 weeks
- The safer way to make sure that we are using the same configuration at NERSC, ANL and Grid is to use containers. James will make the necessary modifications to implement and test containers on the Grid. See Antonio's example on Slack: https://lsstc.slack.com/archives/CJ50YVDD3/p1570546110008700
- If the container solution turns to be too complicated or too long (~10 days) to implement we will revert to the old submission method.
- Before starting we need a tag for `imsim` (@jchiang87 ) and an `lsst_sims` distribution with a set of specific tags. The simplest solution is to ask Scott to provide an official release of `lsst_sims` with the right set of tags. @jchiang87 will provide the list of tags.
- The submission script to be used is available in a github repository. @villarrealas could you please provide the link to the github repository ?
- The final checkpoint files produced by `imsim` should be kept and archived on tape. They may be used to restart the simulation if we decide to add the AGN simulation at a later stage. The compressed checkpoint files produced on the Grid will be stored at CC-IN2P3.
- There are still some configuration problems with the Storage Element (SE) at Lancaster. We will use the SE at CC-IN2P3 as a buffer before moving the files on GPFS.
- A set of validation runs will be simulated by all 3 sites and the image files will be compared.
- James has developed a monitoring tool which is submitting test jobs on the various Grid sites and report spotted problems on a dashboard.
- James will provide some documentation in order to allow more people to submit jobs. We may have to allocate pre-defined "runs" to the Grid submitters to avoid possible authorization problems.
- @villarrealas will decide which site is running which year.

**Comment by villarrealas** [comment] 2019-10-08 18:24
RE GitHub Repo: https://github.com/LSSTDESC/DESC_DC2_imSim_Workflow is now up to date. I will make a tagged version once we have a new version of imSim built.

**Comment by boutigny** [comment] 2019-11-14 16:21
For reference:
James' submission scripts are kept here: https://github.com/LSSTDESC/DC2_grid_scripts

**Comment by boutigny** [comment] 2019-11-18 15:20
@airnandez announced that /cvmfs/gridpp.egi.eu is now visible from all the worker nodes at CC-IN2P3.  That means that the singularity images under /cvmfs/gridpp.egi.eu/lsst/containers are directly usable by the jobs submitted through the grid interfaces

**Comment by katrinheitmann** [comment] 2019-11-27 17:49
I think this is now all sorted out, right? @boutigny and @heather999 : can we close the issue?

**Comment by heather999** [comment] 2019-12-02 15:12
It is fine with me to close this, but @boutigny and others may want to use this area to include additional comments about the ongoing sim production on the grid.

**Comment by boutigny** [comment] 2019-12-02 15:34
Yes, it would be good to keep this open until most of the current grid issues are solved (high failure rate, 100% failure at CC-IN2P3, etc.)

**Comment by katrinheitmann** [comment] 2020-06-07 17:15
The meeting happened, we ran successfully in the end on the grid, @boutigny are you happy to close this now or do we have more issue that we will be investigating? Since the image simulations are basically done now, maybe a brief summary paragraph would be good and then we can close this? Thanks!

**Comment by heather999** [comment] 2020-06-08 13:01
It might also be useful to list what outstanding issues remain and possibly track those via new issues (if there is ongoing investigation)

**Comment by boutigny** [comment] 2020-06-08 13:48
As far as I know there were 3 important remaining issues at the end of the image simulation campaign on the grid:
1. Memory usage requiring to allocate 2x more nodes than necessary
2. Stalled jobs at the end of the processing
3. Missing validation step and difficulty to access to the log files

For 1, If I remember correctly there was some development work on imsim in order to improve the memory management. So it would be nice to try with a newer imsim version and check if the problem is still there.
It is still very unclear what is the problem for 2. My best guess is that it is related to python bad handling of parallelism (note that this problem is not present at NERSC or ANL.
And for 3, we can certainly develop the necessary tools

And yes, I agree that we can close this issue.

**Closed** 2020-06-08 18:27 UTC
Labels: Run 2.2
