### ISSUE TITLE
discrepancy in fluxes predicted by CatSim and PhoSim

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/DC2-production#150] opened 2018-04-13 21:18 UTC
This is copied from an issue in the ImSim repo

https://github.com/LSSTDESC/imSim/issues/78#issuecomment-381262052

CatSim has tools to predict the number of ADU counts from a source.  I noticed that  these tools wer giving significantly different values than what resulted from the `Nphotons` column in PhoSim's centroid files.  It looks like the result is that PhoSim and CatSim use different throughput data.  I'm not sure which is "right" (if that even has meaning at this point)?

I would appreciate input from people such as @johnrpeterson @rhiannonlynne @ivezic 

Here is the detailed description of the situation:

Okay. I think this is a discrepancy between PhoSim and CatSim.

I used PhoSim to simulate 16 sources with a flat SED on the R22S11 chip. This simulation was run in opticsonlymode, which means that there is no atmosphere and no throughput due to the detector. I then compared the gain*ADU value predicted by CatSim with the median of the reported number of photons in the centroid file. The ratio of CatSimValue/PhoSimValue is, for each filter:

u: 0.811
g: 0.915
r: 0.897
i: 0.865
z: 0.859
y: 0.472 (more on this later)

Just doing the most naive thing imaginable and replacing the CatSim `throughputs/baseline/filter_*.dat` data with the data in `$PHOSIM_DIR/data/lsst/filter_*.txt` (taking an angle of incidence=19 degrees, because that matters in PhoSim), I get ratios of CatSimValue/PhoSimValue

u: 0.873
g: 0.973
r: 0.959
i: 0.944
z: 0.930
y: 0.544

PhoSim also has its own files specifying throughput for the lenses and mirrors. If I were being careful, I would try swapping those in as well to see if the ratios go to 1. Regardless: there is obviously a discrepancy between the throughputs being used by PhoSim and those being used by CatSim.

What's up with the y filter?

If you look at `$PHOSIM_DIR/data/lsst/filters_5.txt`, the y-band as non-zero (in fact, almost unity) throughput all the way out to a wavelength of 1.2 microns. In CatSim, the y-band throughput goes to zero at 1.1 microns. Furthermore, I do not know what PhoSim does about the fact that the y-band throughput is unity at the end of the wavelength grid. The SED I simulated has flux out to 2 microns. Maybe PhoSim extrapolates the throughput, which is why CatSim and PhoSim still disagree by a factor of 2, even when I use the PhoSim throughput for y-band.

It seems like people with authority should discuss where the various throughput files are coming from and which is correct.

I am using PhoSim version 3.7.9 and the version of the throughputs repository tagged 2017.01.31

**Comment by danielsf** [comment] 2018-04-13 22:03
Since I created this issue, Zeljko has emailed me and Lynne has come by my office.  This is what Zeljko said


>The filter itself is indeed open towards red (throughput ~ 1). It is the sensor
>QE that kills the overall throughput and brings it to 0 at ~1.1 mic (silicon 
>becomes transparent at that wavelength). 
>
>I would guess that QA effects are modeled directly from first principles in 
>PhoSim (rather than having a QE vs. lambda curve provided).


Lynne said something similar.  The major take-aways from my conversation with Lynne are

- As Zeljko said, the y-band filter should have unity transmission out to 1.2 microns or even beyond.  The copy of `filter_y.dat` in the CatSim `throughputs` repo takes into account that the detector will lose sensitivity after 1.1 microns.  There is an update coming to `throughputs` that ought to bring `filter_y.dat` in line with PhoSim's `filter_5.txt`.

- Because PhoSim tries to simulate the internal physics from first principles, we should not expect the throughputs in `$PHOSIM_DIR/lsst/data` to agree with the throughputs in `throughputs`.  The throughputs in `throughputs` would be the result of averaging the behavior of many photons at each wavelength in PhoSim *if PhoSim and CatSim are in sync with each other*.  The two packages may no longer be in sync, but at some point in the last five years, they were.

- PhoSim contains a directory `$PHOSIM_DIR/validation/baseline` which contains the equivalent of `throughputs/baseline/total_*.dat` resulting from the averaging of many photons at each wavelength.  This is probably what we should be feeding into CatSim if we want to be able accurately predict the number of photons produced by a given object in PhoSim.  Similarly, there is an `imsim` directory in `throughputs` that should contain the throughputs as they were when PhoSim and CatSim were last in sync with each other.

My take away from the entire conversation is that getting CatSim and PhoSim to precisely agree on the number of counts produced by a given object may be a lost cause.

I will investigate what happens when I use the `total_*dat` files provided by PhoSim as the inputs to CatSim.

It also appears that using `opticsonlymode==1` was inappropriate, since that turned off effects due to the detector in PhoSim and, as I have noted, the sensitivity range of the detector is baked into CatSim's `filter_y.dat`.

**Comment by rbiswas4** [comment] 2018-04-13 22:17
> Because PhoSim tries to simulate the internal physics from first principles, we should not expect the throughputs in $PHOSIM_DIR/lsst/data to agree with the throughputs in throughputs. The throughputs in throughputs would be the result of averaging the behavior of many photons at each wavelength in PhoSim if PhoSim and CatSim are in sync with each other. The two packages may no longer be in sync, but at some point in the last five years, they were.

So, aside from `$PHOSIM_DIR/validation/baseline` files, we should see these converge if we counted photons from a single object for several visits in phosim and equivalent total exposure  time in catsim as well.

**Comment by danielsf** [comment] 2018-04-13 22:27
Following my conversation with Lynne, I re-ran my simulations.  This time, I turned the atmosphere and detector on in PhoSim and simulated all catalogs at an airmass of 1.2.  Comparing the PhoSim centroid files to the predictions of CatSim using `throughputs/baseline/total_*.dat`, I found that the ratio of photon counts in CatSim to PhoSim is:

u: 0.421
g: 0.746
r: 0.795
i: 0.811
z: 0.808
y: 0.586

If I redirect CatSim to get its throughputs from `$PHOSIM_DIR/validation/baseline/total_*dat`, I get

u: 1.09
g: 1.01
r: 0.991
i: 1.01
z: 0.995
y: 0.810

The best by far.  These throughputs appear to be consistent with those in `throughputs/imsim/goal/` (as Lynne suspected)

**Comment by danielsf** [comment] 2018-04-13 22:29
@rbiswas4 I think, in addition to the "PhoSim does everything from first principles" issue, there is also an issue of versioning.  If you look at the post I just made, PhoSim is much more consistent with an older version of the throughput curves that is also shipped in `throughputs`.

**Comment by danielsf** [comment] 2018-04-13 22:32
One other difference: the `$PHOSIM_DIR/validation/baseline/total_*.dat` and `throughputs/imsim/goal/total_*.dat` are generated with a standard atmosphere that does not include aerosols.  The new CatSim standard does include aerosols.

**Comment by rbiswas4** [comment] 2018-04-13 22:41
@danielsf 🥇 .  OK, so checking with an updated `total_*.dat` in sync, would be useful. But I do feel that even one percent  (averaged over many visits) is a high degree of variation for the kind of precision tests we would like to do where we want to check accuracy at similar levels, so that the truth must be much more accurate. So, we need to know if this decays with coadds (ie. higher exposure times) or not.

**Comment by danielsf** [comment] 2018-04-13 22:53
@rbiswas4 I see.  I may have misinterpreted your last post.  I can look at what happens as I increase exposure time.

**Comment by rhiannonlynne** [comment] 2018-04-13 22:53
@rbiswas4 so is your plan to generate a truth ADU catalog (from catsim) for a given image and expect that to match the flux you measure for a particular source from phosim + DM?

I would have thought you'd use catsim to generate the truth (mags) of the objects (assuming perfect measurement), then use DM software to measure the phosim mags, calibrated using 'standard stars' picked out of the truth catalog?

**Comment by danielsf** [comment] 2018-04-13 22:54
Before moving on to exposure time, I did a simulation at airmass=2.0.  Using the component throughputs in `throughputs/imsim/goal` and the atmosphere file without aerosols, I get

u: 1.11
g: 1.02
r: 0.990
i: 1.02
z: 1.004
y: 0.809

so, modulo whatever is going on in u and y, we seem to have found the right version of the throughput files.

**Comment by rhiannonlynne** [comment] 2018-04-13 22:56
Note that your atmosphere (in throughputs/imsim/goal) and the atmosphere in PhoSim may not be the same. 
Did you try using the total throughput curves in throughputs/imsim/actual?

**Comment by cwwalter** [comment] 2018-04-13 23:03
Nice job Scott. Just to be super explicit:

The files that are closest (modulo in u and y) are in here:

https://github.com/lsst/throughputs/tree/master/imsim/goal

from 2012. Is that correct?

**Comment by danielsf** [comment] 2018-04-13 23:07
Using the `total_*.dat` in `throughputs/imsim/actual/` and comparing to my airmass 1.2 simulations, I get

u: 1.17
g: 1.02
r: 0.991
i: 0.980
z: 0.967
y: 0.747

using the 'total_*.dat' in 'throughputs/imsim/goal', I get

u: 1.09
g: 1.01
r: 0.991
i: 1.01
z: 0.995
y: 0.810

so  'goal' is actually a better fit than 'actual' (which means this post answers both Lynne and Chris, I guess)

**Comment by danielsf** [comment] 2018-04-13 23:09
(which could mean that PhoSim has been updated since `actual` in such a way that it did a better job of reproducing `goal`; regardless, if `actual` were better, we would probably be in trouble since we are going to need someway to change airmass in these calculations)

**Comment by cwwalter** [comment] 2018-04-13 23:13
So, I'm still a bit unclear on the difference between the repo and the total files in 'validation'.  

You say: "These throughputs appear to be consistent with those in throughputs/imsim/goal/". Do you mean that the file's values look the same?  You can't actually run with those right (because the real input has angular response in it)?  So what do you mean that you ran with the values in 'goal'?

**Comment by danielsf** [comment] 2018-04-13 23:31
The `$PHOSIM_DIR/validation/baseline/*` files are formatted to look like what is in `throughputs`, so: yes, we can just run CatSim with them.

Overplotting the files `$PHOSIM_DIR/validation/baseline/*` look very similar to `throughputs/imsim/goal/*`.  I also get nearly identical results running CatSim with either of those sets of files as inputs.

**Comment by danielsf** [comment] 2018-04-13 23:32
I just ran a test using exposure time = 120s (previous tests have been exposure time = 30s).  The results were effectively identical to the 30s exposure tests.

**Comment by rbiswas4** [comment] 2018-04-14 10:27
@rhiannonlynne 
> @rbiswas4 so is your plan to generate a truth ADU catalog (from catsim) for a given image and expect that to match the flux you measure for a particular source from phosim + DM?
I would have thought you'd use catsim to generate the truth (mags) of the objects (assuming perfect measurement), then use DM software to measure the phosim mags, calibrated using 'standard stars' picked out of the truth catalog?
(which part are you trying to validate -- the DM measurement software or catsim being able to predict the ADU counts in a particular image)

You are correct, we want to compare catsim truth mags to measured (and calibrated) mags or photon counts. But if the comparison has a component due to phosim vs catsim differences at a similar order of magnitude to that we will be interested in, the comparison will mix phosim-catsim differences into the result. So, ideally we want these differences to be subdominant in such comparisons.

**Comment by rbiswas4** [comment] 2018-04-14 11:09
@danielsf 
> I just ran a test using exposure time = 120s (previous tests have been exposure time = 30s). The results were effectively identical to the 30s exposure tests.

What I took your first post to mean was that it was possible that the `throughputs`  with `total*.dat` should be the same as an average over phosim, because phosim simulates the physics leading to QE. So, going to 120 s, this might be expected to reduce the random component by a factor of ~ 2 .  If you still see identical results, then either the difference is not due to some random component, or maybe the randomness is switched off for reproducibility (eg. using the same random seed).

**Comment by RobertLuptonTheGood** [comment] 2018-04-15 15:43
I'm confused.  If we turn off the atmosphere we should get essentially the same results -- in other words, phoSim's GEANTn model of the Si should reproduce the catsim assumptions about Si absorption.  You have to make sure that the temperature of the CCD matches.  You also have to worry about what you mean by the total flux -- if some of the phoSim flux is moved to large radii due to diffraction off the channel stops (and to a lesser extent the parallel gates) that could confuse us at y.

I'd expect these to agree to well under a percent.

Then we can address whether the atmospheres agree.  I would expect that they would also agree to the same sort of precision (I'm making the assumption that the aerosol models are consistent.  I'm not sure how either catSim or phoSim handle the stochastic nature of the aerosols.  I also assume that you're making the same assumptions about the OH -- the other components are presumable consistent as phoSim's taking catSim's barometric pressure and O_3).

**Comment by danielsf** [comment] 2018-04-17 19:38
In an attempt to compare apples to apples, I have hacked the `filter_*.txt` files in `$PHOSIM_DIR/data/lsst/` so that at all angles of incidence, the transmission probability as a function of wavelength agrees exactly with what is found in CatSim's `throughputs/imsim/goal/filter_*.dat`.  I then ran PhoSim with `opticsonlymode==1`, turning off the atmosphere and the quantum efficiency of the detector.  Comparing the number of photons tabulated per source in the PhoSim centroid files with predictions from CatSim, I get significant differences.  Specifically, the ratio of CatSim photons to PhoSim photons in each band is

u: 1.45
g: 1.15
r: 1.09
i: 1.04
z: 1.02
y: 0.96

On the assumption that it may have been some difference in the throughputs and reflectivity of the lenses and mirrors, I further hacked PhoSim so that the reflectivity of each mirror was 1.0, regardless of wavelength, and the transmission and index of refraction of each lens was also 1.0 at all wavelengths.  Applying the same hack to CatSim, I got very similar results when comparing CatSim predicted photons to PhoSim simulated photons.

At this point, I think I need some input from the PhoSim team.  Am I misinterpreting what the various inputs to PhoSim mean?  My version of PhoSim with the hacked filters is in the `catsim_validation` branch of
```
https://danielsf@bitbucket.org/danielsf/phosim_release
```
(my fork of the main `phosim_release` repository).  The configuration file I ran with is `examples/catsim_noatm`.  The catalogs I ran are in `catsim_validation/catalogs/`.  You can try using the `run_catsim_validation.sh` script to generate output similar to what I used.  Note: in this fork the filters have already been hacked to agree with the `filter_*.dat` files here
https://github.com/lsst/throughputs/tree/master/imsim/goal
If you want to further hack the mirrors and lenses to have unity reflectivity and transmission, use the `data/lsst/optics_*_hacked.txt` files.

The script I used to do the CatSim prediction of photons is here
https://github.com/danielsf/CatSimMaintenance/blob/master/phosim_flux/calc_n_photons.py
The script will run without the LSST stack being installed.  You just need to point it to the throughput files you want to use.

Please let me know what I am misunderstanding about PhoSim.

Thank you
@johnrpeterson @sembrosk

**Comment by johnrpeterson** [comment] 2018-04-24 15:44
sorry, i just got pointed to this thread by Daniel.  so in general, phosim's throughput is accurate numerically to basically arbitrary accuracy.  its just a question of doing proper apples to apples tests.

so on the last question, i think the difference is just the mirror reflectivity, right? that would particularly affect the shorter wavelength bins.

**Comment by danielsf** [comment] 2018-04-24 16:07
In one of the tests I did, I set the mirror reflectivity to unity at all wavelengths in both CatSim and PhoSim.  This can be achieved in my fork of the PhoSim repo by using the `optics_*_hacked.txt`, which redirects to `m*_protAl_Ideal_hacked.txt`, in which I set the 3rd column to `1.0` in all rows.  I still saw a discrepancy between the fluxes produced by PhoSim and those predicted by CatSim.  I am open to the possibility that I am predicting the wrong thing in CatSim, but I would need a fresh pair of eyes to look at the `calc_n_photons.py` script I referenced in my previous post, because I have gone over it several times an *I* believe I am doing the right thing (again, I may be wrong).

**Comment by stevkahn** [comment] 2018-04-24 16:48
Robert:

There are detailed effects that may make these calculations disagree.  PhoSim does a photon by photon calculation of propagation through the silicon to the point of photoconversion.  Both the path lengths and the reflection and transmission coefficients at the surfaces are angle dependent.  CatSim does some sort of angle averaged calculation.  Vignetting makes the angle average not exactly correct over the outer regions of the field.  Yes, you right that there are CCD temperature effects in the Y-band, but I would assume that the nominal temperature (-90C) is used in both cases.

Steve

**Comment by danielsf** [comment] 2018-04-24 16:57
In the course of doing this work, I have been naively assuming that if I change the various throughput/reflectivity/etc files in `data/lsst/` so that, for instance, the transmission probability at a given wavelength is the same for every value of angle of incidence, I can essentially turn off the angle dependence of the PhoSim simulation, making it more like the naive CatSim calculation (see the `filter_*_hacked` in my fork of `phosim_release`).  Is this expectation not correct?  Is there no way to hack PhoSim to make it more like CatSim?  I am just trying to find the simplest possible apples-to-apples test at which CatSim and PhoSim agree.  Once I have that, I can start reintroducing PhoSim's various complexities and see where the agreement breaks down.

Thanks.

**Comment by danielsf** [comment] 2018-05-31 23:56
I just completed the following test:

I generated and InstanceCatlaog with 68,229 objects whose SEDs were randomly sampled from the ~ 1,000 galaxy SEDs shipped with CatSim.  For each object, a random redshift was chosen between 0 and 2.  For each SED, redshift combination, I set the magNorm so that CatSim predicted the object should produce 20,000 photons in the r band.  I then simulated this catalog in all six LSST bands and compared the resulting centroid files to the fluxes predicted by CatSim using the `$THROUGHPUTS_DIR/imsim/goal/` bandpasses which seemed to produce the best agreement above.  Note: this simulation at altitude angle=56.2 degrees, or airmass ~ 1.2.  No dust extinction was applied.  All sources were simulated as point source.  Comparing the number of photons predicted by CatSim to the number of photons simulated by PhoSim gave the following distributions (color bars are colored according to the faction of the total number of objects).  Note that the r-band plot will look a little odd, given that this is the band in which I fixed magnorm to produce a set number of photons.

![instcat_ratio_grid_0 txt](https://user-images.githubusercontent.com/1682854/40814118-373b2e54-64f3-11e8-8afd-7852ecef19f4.png)
![instcat_ratio_grid_1 txt](https://user-images.githubusercontent.com/1682854/40814119-3ace79ea-64f3-11e8-992f-eb506fe2af6c.png)
![instcat_ratio_grid_2 txt](https://user-images.githubusercontent.com/1682854/40814122-3f1dc230-64f3-11e8-87c5-c9df46ffbaf1.png)
![instcat_ratio_grid_3 txt](https://user-images.githubusercontent.com/1682854/40814125-41953188-64f3-11e8-8ee0-4bd9762d8dd0.png)
![instcat_ratio_grid_4 txt](https://user-images.githubusercontent.com/1682854/40814127-436c0130-64f3-11e8-9497-803c120eea2e.png)
![instcat_ratio_grid_5 txt](https://user-images.githubusercontent.com/1682854/40814129-455f05e6-64f3-11e8-8c66-4e9a070f619e.png)

Comparing predicted colors gives the following plots.

![u_g_color_plot](https://user-images.githubusercontent.com/1682854/40814148-65c89cac-64f3-11e8-9f5a-0e9b3736e951.png)
![g_r_color_plot](https://user-images.githubusercontent.com/1682854/40814151-68b2ae62-64f3-11e8-837b-c54878f29c7b.png)
![r_i_color_plot](https://user-images.githubusercontent.com/1682854/40814154-6b032e9e-64f3-11e8-8cba-9cc130a8a087.png)
![i_z_color_plot](https://user-images.githubusercontent.com/1682854/40814156-6d48e4f0-64f3-11e8-809c-f6645e12b03d.png)
![z_y_color_plot](https://user-images.githubusercontent.com/1682854/40814159-6f714c40-64f3-11e8-87c7-5bb5c2ba451c.png)

I do not see any obvious structure in any of these plots, which, I suspect, means that the difference between PhoSim and CatSim is due to a difference in the throughputs used by CatSim as compared the effective throughput used by PhoSim.

**Comment by rhiannonlynne** [comment] 2018-06-01 00:09
Hi Scott,

Nice .. is there any correlation with location in the focal plane?

Lynne

**Comment by danielsf** [comment] 2018-06-01 16:42
For people who don't think in magnitudes, here are plots of flux ratios versus -2.5*log10(phosim_flux)

(I will investigate focal plane dependence next, Lynne)

![u_flux_plot](https://user-images.githubusercontent.com/1682854/40852660-02e52064-6580-11e8-9c13-534ded426377.png)
![g_flux_plot](https://user-images.githubusercontent.com/1682854/40852662-06767214-6580-11e8-812d-edbeba299e3c.png)
![r_flux_plot](https://user-images.githubusercontent.com/1682854/40852672-08ea8724-6580-11e8-82f8-cc52e1408e23.png)
![i_flux_plot](https://user-images.githubusercontent.com/1682854/40852675-0ba84e60-6580-11e8-804a-30b0cf5ed78d.png)
![z_flux_plot](https://user-images.githubusercontent.com/1682854/40852681-0eedf822-6580-11e8-8e86-a2a2f9f06fbd.png)
![y_flux_plot](https://user-images.githubusercontent.com/1682854/40852687-1125fb6c-6580-11e8-8590-02db2dc7ef92.png)

**Comment by danielsf** [comment] 2018-06-01 21:46
@rhiannonlynne I see no evidence of variation across the focal plane.  In the plots below, I bin the sources into 1mm by 1mm (so: 50 pixel by 50 pixel) bins, and plot the median delta_color as well as the most extreme color deviation in each bin.  There does not appear to be any structure in any of the colors.

![focal_plane_dcolor_u_g](https://user-images.githubusercontent.com/1682854/40864878-890ccd52-65aa-11e8-82dc-4abc8da0c7e9.png)
![focal_plane_dcolor_g_r](https://user-images.githubusercontent.com/1682854/40864879-8c239aca-65aa-11e8-8ce0-15729fb5ce1b.png)
![focal_plane_dcolor_r_i](https://user-images.githubusercontent.com/1682854/40864881-8e9acc60-65aa-11e8-92df-27f1772b4d5f.png)
![focal_plane_dcolor_i_z](https://user-images.githubusercontent.com/1682854/40864884-91dc8080-65aa-11e8-9e69-7be715164894.png)
![focal_plane_dcolor_z_y](https://user-images.githubusercontent.com/1682854/40864888-95917924-65aa-11e8-8c9c-c3e91787c93a.png)

**Comment by rhiannonlynne** [comment] 2018-06-01 21:56
Thanks for checking! I was wondering if atmosphere or filter throughout as
a function of location in focal plane could be changing things, but looks
like no.

**Comment by katrinheitmann** [comment] 2019-04-06 15:48
@danielsf Has this ever been cleared up? If yes, I think it would be good to have a summary statement and close it out. If not, do we need to worry about this and what would we do?

**Comment by danielsf** [comment] 2019-04-08 15:03
The conclusion was: there is no good way to do this comparison since PhoSim's throughput curve is an emergent property of the physics it is simulating, and there is no good way to turn off the various effects (e.g. set the lens transmissivity by hand, etc.).

I think that last set of plots represents the best agreement we can hope to get.

**Closed** 2019-06-25 20:49 UTC
