### ISSUE TITLE
Low density on tract 4852/patch 1,5 on Run2.2i DR6 WFD

### ISSUE THREAD

**Issue by plaszczy** [LSSTDESC/DC2-production#408] opened 2020-12-10 10:49 UTC
![tract_chelou](https://user-images.githubusercontent.com/11886566/101762487-cad3e580-3add-11eb-897c-afb465d62f01.png)
* @plaszczy noticed a patch with low density

**Comment by plaszczy** [comment] 2020-12-10 10:52
That was confirmed by @fjaviersanchez :it was eliminated because of the "good" selection. because of ovjects that had 'base_PixelFlags_flag_clipped'. 
It is not present on DR2.

**Comment by johannct** [comment] 2020-12-10 12:42
see https://lsstc.slack.com/archives/CM6MF33UG/p1607440268069500 for more on this.
I tried to track down a pathological calexp but failed. In the meantime it appears that the coaddDriver outputs have inconsistent timestamp, so I am going to rerun it, keeping the warps but removing the final products so that they possibly get updated.

**Comment by wmwv** [comment] 2020-12-10 13:33
Thanks, @johannct .  I am very interested in the results of a re-run.  The special behavior of this patch makes me think that there was a temporary configuration problem, or that this patch was run with a different configuration than all the others.

**Comment by johannct** [comment] 2020-12-10 13:49
Before setting the coaddDriver output I just chcked the supreme exposure map for 4852, and it looks perfectly sane, so whatever happened to this patch is of a different nature than the previously spotted failures
![dc2_testing_04852_i_exptime_sum](https://user-images.githubusercontent.com/586081/101780428-d7186c80-3af6-11eb-85da-8eef01407852.png)

**Comment by wmwv** [comment] 2020-12-10 14:31
@fjaviersanchez found:
"""
the hole there in DR6 corresponds to objects with 'base_PixelFlags_flag_clipped' that have been eliminated when you apply the good cut (btw, I also checked DR2 and there's no hole there when you apply the good cut).
Below is the plot of DR6 galaxies in the tract that @stefplaz mentioned with base_PixelFlags_flag_clipped==True :
"""

![image (1)](https://user-images.githubusercontent.com/3201257/101785247-89860a80-3aca-11eb-9356-e423506e707f.png)

**Comment by wmwv** [comment] 2020-12-10 14:32
@fjaviersanchez continues:
"""
(my map is flipped with respect to Stéphane's)


and a higher resolution zoom-in:
"""

![image (2)](https://user-images.githubusercontent.com/3201257/101785320-9efb3480-3aca-11eb-886d-0c21784c0f9e.png)

**Comment by wmwv** [comment] 2020-12-10 14:53
@johannct notes that:
"""
update : looking at the occurrence of the value True for this flag in 'deepCoadd_meas' I get
u, 32
g, 0
r, 26
i, 29134
z, 32
y, 27
So of course it is the reference band which is pathological.....
"""

**Comment by wmwv** [comment] 2020-12-10 16:09
@johannct What numbers do you get for the occurrence of `base_PixelFlags_flag_clipped` in the next patch over?  E.g., tract 4852, patch 1,4.

**Comment by heather999** [comment] 2020-12-10 16:18
Recall this issue: https://github.com/LSSTDESC/DC2-production/issues/400 where due to the processing at NERSC where we tried to reuse the existing warps from CC, it was found a number of warp files appear to be corrupt.  Given the datestamps on the files, it seemed connected with the disk filling up at CC back in May.  While I haven't completely finished, I do have a list of bad warps. A 130 of them in the i band for tract 4852, include patch 1,5 and 139 in patch 1,4 There are many other bad warps in 4852 for some other patches. I do wonder if these warps should be regenerated.   I started to collect a list here at CC: `/sps/lsst/users/hkelly/dr6-warps-checks` There's a specific list for 4852 1,5 here: `/sps/lsst/users/hkelly/dr6-warps-checks/bad-i-tract-4852-1,5.out`

**Comment by johannct** [comment] 2020-12-10 16:40
Hmm as far as I can tell there are 130 warp files in your list, and 130 warps in the rerun directory.... so that would mean that they are all bad somehow? It would be good to understand exactly what is wrong with them then, because fitsinfo does not complain for any of them.

**Comment by jchiang87** [comment] 2020-12-10 16:45
For many of the corrupted files, one needs to explicitly read in and access the data section of one of the image extensions to see an error.   I'd be surprised if the files were corrupted at the time of the coadd generation since things would have crashed, but it's worth following up on.   Regardless, corrupted files should be identified and moved out of the way.

**Comment by johannct** [comment] 2020-12-10 16:55
yes I was hoping that supreme was doing that as well...... I do not understand. Ok so if you confirm that they should all be deleted I will remove them and relaunch coaddDriver a third time.

**Comment by heather999** [comment] 2020-12-10 16:56
See updated comment :) There are some bad warps, but not in 4852 i band.  I'm going through the logs again though to see if the other bands show anything for that particular tract.

**Comment by johannct** [comment] 2020-12-10 17:06
In [149]: d=[] 
     ...: for f in ['u','g','r','i','z','y']: 
     ...:     id={'tract':4852,'patch':'1,4','filter':f} 
     ...:     dd=butler.get('deepCoadd_meas',dataId=id) 
     ...:     print('{} {}'.format(f,len(np.where(dd['base_PixelFlags_flag_clipped']==True)[0]))) 
     ...:     d.append(dd) 
     ...:     
     ...:                                                                                                                                                                                                          
u 28
g 13
r 18
i 29
z 26
y 19

In [150]: d=[] 
     ...: for f in ['u','g','r','i','z','y']: 
     ...:     id={'tract':4852,'patch':'1,5','filter':f} 
     ...:     dd=butler.get('deepCoadd_meas',dataId=id) 
     ...:     print('{} {}'.format(f,len(np.where(dd['base_PixelFlags_flag_clipped']==True)[0]))) 
     ...:     d.append(dd) 
     ...:     
     ...:                                                                                                                                                                                                          
u 32
g 0
r 26
i 29134
z 32
y 27

**Comment by erykoff** [comment] 2020-12-10 17:14
Has anybody opened all the warps?  If an extension was all zeros or something that would be an issue and still be a valid fits file.
Meanwhile, suprême does not open the individual warps in the mode that I ran on DC2, because this was orders of magnitude too slow due to where the warps live on the file system.

**Comment by jchiang87** [comment] 2020-12-10 17:18
The test code snippet I proposed opens each image extension and accesses the shape of the data arrays.  That's sufficient to trigger the same error that we saw in the coaddition task.  It didn't look at any array values.

**Comment by erykoff** [comment] 2020-12-10 17:20
I think we need to look at the values themselves, because this is setting the CLIPPED flag so presumably there are numbers here but they are crazy outliers.

**Comment by jchiang87** [comment] 2020-12-10 17:22
I'll have a look.

**Comment by johannct** [comment] 2020-12-10 17:26
Hmmm I took the last one randomly, to check how the code would go :
In [1]: from astropy.io import fits                                                                                                                                                                                
In [2]: hdu=fits.open('rerun/run2.2i-coadd-wfd-dr6-v1-grizy/deepCoadd/i/4852/1,5/warp-i-4852-1,5-995008.fits')                                                                                                     
In [11]: hdu[1].shape,np.min(hdu[1].data),np.max(hdu[1].data)                                                                                                                                                      
Out[11]: ((4200, 4200), nan, nan)

**Comment by erykoff** [comment] 2020-12-10 17:27
There can be nans if they're masked, I think you need `np.nanmin`

**Comment by johannct** [comment] 2020-12-10 17:28
In [15]: hdu[1].shape,np.nanmin(hdu[1].data),np.nanmax(hdu[1].data)                                                                                                                                                
Out[15]: ((4200, 4200), -459.5638, 131863.9)

**Comment by wmwv** [comment] 2020-12-10 17:30
There are two questions:
1. Is there one bad image?
2. Why does one bad image propagate to all of the pixels in the coadd.  The thresholds to map from individual image mask values to coadd mask values should be at least (?) 20%.  One image shouldn't propagate like this.

**Comment by johannct** [comment] 2020-12-10 17:30
ok looping now.....

**Comment by johannct** [comment] 2020-12-10 17:32
@wmwv I think we are in paranoid check mode here, we turn all the stones

**Comment by johannct** [comment] 2020-12-10 17:34
In [18]: for file in files : 
    ...:     hdu=fits.open(file) 
    ...:     print(hdu[1].shape,np.nanmin(hdu[1].data),np.nanmax(hdu[1].data)) 
    ...:                                                                                                                                                                                                           
(4200, 4200) -221.08604 133905.1
(4200, 4200) -214.76836 139060.38
(4200, 4200) -366.0075 132893.77
(4200, 4200) -228.26071 127752.06
(4200, 4200) -359.60248 123011.17
(4200, 4200) -410.39493 123648.72
(4200, 4200) -287.60092 134028.53
(4200, 4200) -297.4834 142707.14
(4200, 4200) -343.23798 134039.9
(4200, 4200) -333.2711 94684.02
(4200, 4200) -429.60797 134553.14
(4200, 4200) -240.8877 139433.05
(4200, 4200) -253.50287 132108.03
(4200, 4200) -313.1606 86863.28
(4200, 4200) -227.18558 137615.8
(4200, 4200) -313.3414 138924.62
(4200, 4200) -228.28221 138908.22
(4200, 4200) -233.07065 136456.36
(4200, 4200) -238.40208 140100.1
(4200, 4200) -359.60675 131295.97
(4200, 4200) -297.1659 130965.8
(4200, 4200) -296.82626 122973.234
(4200, 4200) -389.96426 126481.37
(4200, 4200) -209.39848 134179.42
(4200, 4200) -220.55402 135111.73
(4200, 4200) -225.01671 129270.61
(4200, 4200) -241.86803 136417.08
(4200, 4200) -263.54977 122629.26
(4200, 4200) -232.34193 123612.34
(4200, 4200) -242.83937 138155.8
(4200, 4200) -359.29358 139312.73
(4200, 4200) -384.5748 138924.84
(4200, 4200) -198.96458 997.3174
(4200, 4200) -327.1076 141224.86
(4200, 4200) -459.5638 131863.9
(4200, 4200) -218.9993 143118.56
(4200, 4200) -355.44714 131582.31
(4200, 4200) -335.10596 121496.414
(4200, 4200) -220.7141 141601.34
(4200, 4200) -224.05415 145167.67
(4200, 4200) -235.33553 139298.52
(4200, 4200) -348.3461 130177.41
(4200, 4200) -244.94116 113448.625
(4200, 4200) -407.3234 141324.77
(4200, 4200) -344.74213 99353.83
(4200, 4200) -279.4023 126072.96
(4200, 4200) -375.81897 136397.64
(4200, 4200) -384.42545 130244.15
(4200, 4200) -330.38043 141549.83
(4200, 4200) -285.0421 133313.84
(4200, 4200) -224.46022 147216.33
(4200, 4200) -342.903 132111.72
(4200, 4200) -221.27449 135182.61
(4200, 4200) -223.57861 129118.28
(4200, 4200) -245.40088 136870.05
(4200, 4200) -226.03519 124667.016
(4200, 4200) -365.07425 134581.2
(4200, 4200) -358.88992 131584.75
(4200, 4200) -361.09113 126800.15
(4200, 4200) -408.5616 137013.6
(4200, 4200) -276.30737 131298.9
(4200, 4200) -234.86754 121050.64
(4200, 4200) -230.76772 143862.1
(4200, 4200) -405.2909 135016.33
(4200, 4200) -383.11908 136644.48
(4200, 4200) -362.63193 130828.805
(4200, 4200) -361.85605 104724.445
(4200, 4200) -298.3697 139430.66
(4200, 4200) -349.76886 135952.77
(4200, 4200) -234.52693 131596.16
(4200, 4200) -450.40366 127424.664
(4200, 4200) -266.98944 148013.55
(4200, 4200) -239.36635 134346.94
(4200, 4200) -405.66418 139318.78
(4200, 4200) -407.34253 128650.664
(4200, 4200) -270.9116 132728.92
(4200, 4200) -232.91992 137628.5
(4200, 4200) -380.22607 139010.3
(4200, 4200) -390.6479 135483.84
(4200, 4200) -430.38373 103387.22
(4200, 4200) -369.58444 136016.9
(4200, 4200) -236.92389 133908.39
(4200, 4200) -343.90466 114249.07
(4200, 4200) -234.69402 135889.78
(4200, 4200) -275.37216 133662.61
(4200, 4200) -231.78294 139231.02
(4200, 4200) -306.9835 143125.11
(4200, 4200) -430.68283 135528.64
(4200, 4200) -256.94614 132847.14
(4200, 4200) -283.16025 142584.52
(4200, 4200) -253.36618 138652.23
(4200, 4200) -241.82642 122275.39
(4200, 4200) -241.08351 127364.86
(4200, 4200) -335.7297 128853.19
(4200, 4200) -269.1661 135810.47
(4200, 4200) -361.54834 126647.58
(4200, 4200) -243.64369 132435.92
(4200, 4200) -310.02405 145569.95
(4200, 4200) -303.22217 133875.17
(4200, 4200) -325.29352 134571.8
(4200, 4200) -358.8536 131591.53
(4200, 4200) -361.1473 133469.12
(4200, 4200) -298.18802 7121.0894
(4200, 4200) -413.1947 129937.836
(4200, 4200) -219.54723 131380.53
(4200, 4200) -329.9853 124610.19
(4200, 4200) -215.26097 127490.734
(4200, 4200) -215.66096 128880.81
(4200, 4200) -344.53 131975.08
(4200, 4200) -190.59291 49608.266
(4200, 4200) -263.8326 133168.27
(4200, 4200) -221.83551 136502.84
(4200, 4200) -333.5346 131394.84
(4200, 4200) -212.17023 127306.88
(4200, 4200) -230.33888 131760.94
(4200, 4200) -242.73006 135753.66
(4200, 4200) -368.48984 130084.7
(4200, 4200) -210.56142 136671.72
(4200, 4200) -219.70772 134464.67
(4200, 4200) -234.63768 136564.45
(4200, 4200) -207.26266 99546.4
(4200, 4200) -225.53851 143131.39
(4200, 4200) -308.30362 143474.28
(4200, 4200) -323.02667 124720.05
(4200, 4200) -275.3604 129618.72
(4200, 4200) -217.21942 139432.89
(4200, 4200) -301.8557 133558.06
(4200, 4200) -258.93634 146225.88
(4200, 4200) -223.41513 134532.22
(4200, 4200) -351.75363 136545.86

**Comment by wmwv** [comment] 2020-12-10 17:37
> @wmwv I think we are in paranoid check mode here, we turn all the stones

Agreed.  The discussion so far had been focused on finding the bad image (item 1).  My point was to also encourage consideration of Item 2, what went on in the coadd config.

**Comment by johannct** [comment] 2020-12-10 17:38
so a priori there is no blatant issue with one of the warps

**Comment by jchiang87** [comment] 2020-12-10 17:39
@johannct Can you also check extensions 2 and 3?  the variance and mask extensions?

**Comment by johannct** [comment] 2020-12-10 17:41
extension 3 has nanmax systematically set to 'inf'

**Comment by erykoff** [comment] 2020-12-10 17:41
I generally agree that there isn't a blatant issue, and I think that @wmwv makes a very good point that whatever is going wrong is propagating to all the pixels in the coadd, which is hard for one image to do! I wonder if it's also possible to rerun the coadd with the existing warps and see if the problem is still there?  Presumably we wouldn't have to even run source detection or multiband, just look at the coadd mask plane.

**Comment by erykoff** [comment] 2020-12-10 17:42
Extension 3 is ...?

**Comment by johannct** [comment] 2020-12-10 17:42
mask? according to @jchiang87

**Comment by jchiang87** [comment] 2020-12-10 17:43
or variance, I can't remember which offhand, but the variance values should be obvious.

**Comment by johannct** [comment] 2020-12-10 17:43
@erykoff , this is already running

**Comment by johannct** [comment] 2020-12-10 17:44
> or variance, I can't remember which offhand, but the variance values should be obvious.

typically (4200, 4200) 4162.3 inf for ext 3
typically (4200, 4200) 0 3104 for ext2

**Comment by erykoff** [comment] 2020-12-10 17:44
Then 2 must be mask, 3 is inverse variance?

**Comment by johannct** [comment] 2020-12-10 17:49
I do not know how a config could change for a single patch out of the blue..... @wmwv which datasetType would you look at? There is no `deepCoadd_meas_config` but there is a `deepCoadd_forced_config`

**Comment by jchiang87** [comment] 2020-12-10 17:55
There is one image that has a very different range of pixel values:
```
(4200, 4200) -198.96458 997.3174
```
Most max pixel values are ~100k.   Maybe this is an outlier frame worth looking at?

**Comment by erykoff** [comment] 2020-12-10 18:32
This is what the mask plane looks like on 1,5 (the bad one) and 1,6 (neighboring okay) from the repo at nersc.  The bit 2**14=16384 is the "clipped" bit.  And it is set almost everywhere on 1,5 and not at all on 1,6, and not following any of the input images.  So something went 🤪 here.  
![image](https://user-images.githubusercontent.com/5167891/101814378-ea194580-3ad2-11eb-99e5-270133eba415.png)

**Comment by erykoff** [comment] 2020-12-10 18:33
This is from, e.g, `/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/desc_dm_drp/v19.0.0-v1/rerun/run2.2i-coadd-wfd-dr6-v1-grizy/deepCoadd/i/4852/1,5.fits`.  Don't need to look at the sources/run multiband to see the problem.

**Comment by jchiang87** [comment] 2020-12-10 18:36
The pattern on the left indicates that it is a single image that is causing that bit to be set.

**Comment by erykoff** [comment] 2020-12-10 18:38
The bit is set on both sides of a chip gap ... maybe a single visit, but not a single PVI/calexp/warp, no?

**Comment by johannct** [comment] 2020-12-10 18:39
Good catch @jchiang87 je case you spotted is  rerun/run2.2i-coadd-wfd-dr6-v1-grizy/deepCoadd/i/4852/1,5/warp-i-4852-1,5-893769.fits
![ds9](https://user-images.githubusercontent.com/586081/101815113-56ba3180-3b1f-11eb-94a4-c73790333887.png)

God switched on a light bulb....

**Comment by jchiang87** [comment] 2020-12-10 18:39
Yes, a single visit, but that would still correspond to a single warp image that combines the different PVI that overlap with it.

**Comment by erykoff** [comment] 2020-12-10 18:41
@jchiang87 Ah yes, duh.  @johannct seems problematic.

**Comment by johannct** [comment] 2020-12-10 18:43
this is a bit tougher.... I have no better way than to open them all

**Comment by erykoff** [comment] 2020-12-10 18:48
I think that the `suprême` input map can help here.  Give me a moment...

**Comment by jchiang87** [comment] 2020-12-10 18:48
I think the pixels in chip gaps should all be nan-valued in the image itself, so the number of nans would match or be close to the number of non-clipped pixels in the coadd...could try comparing those numbers to see....

**Comment by jchiang87** [comment] 2020-12-10 18:55
Another test is that there are at least 5 CCDs contributing to that warp.  4 or fewer is more typical.  I think the number of contributing CCDs is in the warp headers somewhere.

**Comment by johannct** [comment] 2020-12-10 19:10
I did not find it

**Comment by jchiang87** [comment] 2020-12-10 19:27
Looking at the tracts_mapping.sqlite3 file, there are 33 visits with > 4 ccds contributing in i-band.  Here they are
```
919561 5
945676 5
420877 5
211473 5
919601 5
665665 6
1157699 5
437323 5
1185891 5
665703 6
678509 5
685691 5
994964 5
994965 5
906938 6
995008 5
211148 5
211179 5
458497 5
204555 5
965400 5
269088 5
1000776 5
1000781 6
269134 5
1209684 5
1212791 5
434049 5
1165737 5
518059 5
1209263 5
420826 5
200191 5
```
with the number of CCDs contributing in the second column.

**Comment by erykoff** [comment] 2020-12-10 19:35
The offender is 665703 according to the supreme input map. 
![image](https://user-images.githubusercontent.com/5167891/101820711-d9b99880-3adb-11eb-9fd2-0674460ef92b.png)

**Comment by erykoff** [comment] 2020-12-10 19:41
Where do the warps live at nersc?

**Comment by jchiang87** [comment] 2020-12-10 19:45
They would be here:
```
/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/desc_dm_drp/v19.0.0-v1/rerun/run2.2i-coadd-wfd-dr6-v1-grizy/deepCoadd/i/4852/1,5
```
but that folder is empty. The originals, if they are still around, would be at CC-IN2P3.

**Comment by erykoff** [comment] 2020-12-10 19:47
I thought that @heather999 put them somewhere else?  Or maybe I'm mis-remembering.  But if we don't have the warps at nersc, I can't do anything else at the moment, and hopefully @johannct will notice something strange with 665703.

**Comment by johannct** [comment] 2020-12-10 19:48
![Uploading ds9.png…]()

**Comment by erykoff** [comment] 2020-12-10 19:57
Seems kind of empty, but maybe the scale ... does it look strange compared to another visit warp?

**Comment by johannct** [comment] 2020-12-10 19:58
not really.....

**Comment by jchiang87** [comment] 2020-12-10 20:02
fwiw, here's the tracts_mapping info on that warp:
```
          id  tract   patch   visit  detector filter layer
194  6720042   4852  (1, 5)  665703       133      i      
195  6720045   4852  (1, 5)  665703       134      i      
196  6720081   4852  (1, 5)  665703       141      i      
197  6720201   4852  (1, 5)  665703       163      i      
198  6720205   4852  (1, 5)  665703       164      i      
199  6720245   4852  (1, 5)  665703       171      i      
```
Having looked at a few of these calexps, thing seem fine, but I only looked at the image data.
```
/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/desc_dm_drp/v19.0.0-v1/rerun/run2.2i-calexp-v1/calexp/00665703-i
```

**Comment by jchiang87** [comment] 2020-12-10 20:05
@johannct Which SRS log file corresponds to the creation of that warp?  There may be clues there.

**Comment by johannct** [comment] 2020-12-10 20:09
/sps/lsst/users/descprod/Pipeline2/Logs/DC2DM_DRP/2.9/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/024/043/007/001/logFile.txt

**Comment by wmwv** [comment] 2020-12-10 20:56
> But if we don't have the warps at nersc, 

We explicitly decided that we didn't need to keep these intermediate products at NERSC.

**Comment by erykoff** [comment] 2020-12-10 21:10
Right!  We have the calexps somewhere but not the warps (or the wasps for that matter).  @johannct can you put the warps for 665703 and, say, 174550 some place on nersc scratch so that I can poke at them?

**Comment by johannct** [comment] 2020-12-10 21:17
both  in /global/cscratch1/sd/erykoff/johannct for others than Eli who want to look.

**Comment by erykoff** [comment] 2020-12-10 21:23
Will need the mode changed to 666 and we're good to go.  Thanks!

**Comment by wmwv** [comment] 2020-12-10 21:43
> The offender is 665703 according to the supreme input map.

Was this statement based just on a visual recognition of the pattern?

**Comment by erykoff** [comment] 2020-12-10 21:47
I looked at the pattern of all of the input visits and that was the only one that matched.

**Comment by wmwv** [comment] 2020-12-10 21:47
Hmmm... I ask because, as you're likely similarly looking at right now, there doesn't seem to be anything obviously wrong with that warp.

**Comment by erykoff** [comment] 2020-12-10 21:50
The weight map pattern looks very different between the two.  Don't know which would be "correct" I've never looked at a warp weight map, nor do I know how this could cause a problem...

**Comment by wmwv** [comment] 2020-12-10 21:54
> The weight map pattern looks very different between the two.

Do you mean at the pixel level, or the moire pattern when zoomed out and resampled?

**Comment by erykoff** [comment] 2020-12-10 21:54
Oh I have an idea.  There was a bug in the coadd code that was fixed I'm pretty sure after this processing that the psf matched warps would screw up the scaling if the coadd had a bad psf.  And how did it have a bad psf?  It was choosing the center of the warp or something like that.  And there's no psf model at the center of the warp for 665703.

**Comment by wmwv** [comment] 2020-12-10 21:56
Hmm... interesting.

The psfMatchedWarp images look to have the same scaling here.

**Comment by erykoff** [comment] 2020-12-10 21:57
![image](https://user-images.githubusercontent.com/5167891/101834709-8d785380-3aef-11eb-8aa1-105d27c2795b.png)

**Comment by jchiang87** [comment] 2020-12-10 21:57
@erykoff Very interesting! Though I'd be surprised if this was the only warp in all of DC2 where this occurred.

**Comment by wmwv** [comment] 2020-12-10 21:57
But you're saying that there's some step that asks about the PSF model of the warp and that selects the center to be typical.  So the bug is after the psfMwatchedWarp generation and part of the combining into the coadd?

**Comment by wmwv** [comment] 2020-12-10 22:00
Okay, completely spit-balling here.  But maybe the bug is as @erykoff identified above, then combined with the mask setting having some bug where the fractional threshold to propagate a mask pixel to the coadd mask value behavior differently if there are 5 images or more.

**Comment by erykoff** [comment] 2020-12-10 22:01
Ah, I was wrong, it's the other way around: https://lsstc.slack.com/archives/C2JPXB4HG/p1590785611140900 .  The problem is that when making the coadd psf for detection things can go into bad regions.  But this is something different, but I fear it might be related.  But then again, you'd think there would be other warps where this happened!  So I think it's a coincidence.

**Comment by wmwv** [comment] 2020-12-10 22:01
Because I agree with @jchiang87 's point that the number of times one gets the PSF in the center to not be a valid PSF should go as something like the fractional area of the chip gaps.

**Comment by erykoff** [comment] 2020-12-10 22:02
The 5 images or more is in terms of the stacked depth in the coadd and there are >> 5 images everywhere here.

**Comment by wmwv** [comment] 2020-12-10 22:04
Oh, sorry, I'm an idiot.  I totally misunderstood @jchiang87 table above.  He was counting number of CCDs contributing to the warp for a given visit.  That makes sense.

**Comment by wmwv** [comment] 2020-12-10 22:09
@erykoff What does the PSF model look like for those warps?

I have great confidence in your ability to assess whether nor not a given PSF model is good.  But if it's otherwise useful, I grabbed a few more warps and put them on NERSC in `/global/cscratch1/sd/wmwv/DC2_Run2.2i/debug_bad_warp` if you want to compare.

**Comment by erykoff** [comment] 2020-12-10 22:13
I have no confidence in my ability to make images of stack psf models...but I can say that the size of the psf for the bad image is smaller?  But now I'm totally fishing and nothing is obviously fishy.

**Comment by jchiang87** [comment] 2020-12-10 22:40
Here are images of the psfs from the calexps for all six sensor-visits contributing to that warp:
![665703_4852_1,5_psfs](https://user-images.githubusercontent.com/1994473/101838309-3e352180-3af5-11eb-8ac7-7c70974ea5a9.png)
These are evaluated at the center of the ccd.  And the output of `psf.computeShape()` for each:
```
133 (ixx=1.99657594373448, iyy=2.050492953217776, ixy=-0.011098628584589033)
134 (ixx=2.019505530391281, iyy=2.101699763461495, ixy=-0.006890655147915128)
141 (ixx=2.029050756326062, iyy=2.083832430512826, ixy=-0.0032894101846721816)
163 (ixx=1.9745718082384986, iyy=2.053081621210872, ixy=-0.005349000670642242)
164 (ixx=2.0043181345859926, iyy=2.057558593012063, ixy=-0.002385396921082846)
171 (ixx=2.0112337378367817, iyy=2.1142107505264067, ixy=0.0011369217832696897)
```
The first column is the detector number.  The values all look similar to other CCDs in this visit.

**Comment by johannct** [comment] 2020-12-10 22:46
coaddDriver finished:

**Comment by erykoff** [comment] 2020-12-10 22:48
Can you shoot the deepCoadd file over to nersc?

**Comment by johannct** [comment] 2020-12-10 22:52
done

**Comment by erykoff** [comment] 2020-12-10 22:53
So ... the new 1,5.fits that @johannct just processed looks perfectly fine in the mask plane.

**Comment by erykoff** [comment] 2020-12-10 22:54
Here's what it looks like.  So was this some sort of transient processing failure?  How can we determine that?
![image](https://user-images.githubusercontent.com/5167891/101839639-93723280-3af7-11eb-8bd4-a3c92a48fcfc.png)

**Comment by johannct** [comment] 2020-12-10 22:56
ok....... the only thing clear is that the dates are inconsistent : warps timestamps are after coadd timestamps. The log does not seem to help at all.... This is bad.

**Comment by johannct** [comment] 2020-12-10 22:57
I'll move to multiband so it is running during the night CET. I will rename the current outputs as I did for coaddDriver

**Comment by plaszczy** [comment] 2020-12-14 09:03
I missed the conclusion (if any). was it a system glitch?

**Comment by johannct** [comment] 2020-12-15 08:32
Looks like. Of an unknown kind. @heather999 1,5 is ready at CC for pickup.

**Comment by plaszczy** [comment] 2020-12-15 09:03
I checked all the patches, it seems only this one was affected. can we close the issue?

**Comment by johannct** [comment] 2020-12-15 11:07
not before the reprocessed patch is analyzed :)

**Comment by plaszczy** [comment] 2021-01-06 11:07
to start well the year, here is the famous before/after plot. nice job.
![bad_v1](https://user-images.githubusercontent.com/11886566/103761906-570af700-500f-11eb-82c3-5659233809ac.png)
![good_v2](https://user-images.githubusercontent.com/11886566/103761916-5d00d800-500f-11eb-8c00-77d8746edcc9.png)

**Comment by heather999** [comment] 2021-01-06 13:14
Are we willing to use the above as sufficient validation so we can move ahead and make a DR6-v2 release?

**Comment by johannct** [comment] 2021-01-06 13:20
I think so

**Comment by plaszczy** [comment] 2021-01-06 14:27
I'd like to run a few additional checks that I usually report in https://lsst.lal.in2p3.fr/lalwiki/LSS/Run22 but that I did not performed in v1 since I got stuck on this patch problem.

**Comment by plaszczy** [comment] 2021-01-07 13:39
I (mildly) tortured the new data and can't find any obvious flaw, so on my side its OK for release

**Comment by johannct** [comment] 2021-01-07 13:40
Thanks @plaszczy Following this and the discussion at DM-DA yesterday, I am closing this issue.

**Closed by johannct** 2021-01-07 13:40 UTC
