### ISSUE TITLE
2.0i e-image files location and utility

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2-production#258] opened 2018-08-28 21:26 UTC
There is a new issue in the imSim repo: https://github.com/LSSTDESC/imSim/issues/146

"Add the option to create `raw` files directly, skipping the eimage generation step." I wanted to start a conversation about it, but I thought not all of the people with important insights into the problem are following the imSim repo so I thought I would start the conversation here instead.

From talking to Jim etc, I understand the motivation for keeping only the amplifier files for 2.0i (and not keeping the e-image files which contain the true pixel information) would be to save disk space.  This is certainly understandable!  However, this intermediate product is a very important output (corresponding to the results before we run the collected electrons through the amps and readout chain).  Typically we would certainly keep these.  Producing them is the most expensive part of the process. We can produce the amplifier files with gains, xtalk etc from them very quickly.

I imagine we might want to rerun, making the amplifier files with updated paramaters, such as new CTI, or per sensor xtalk coefficients etc. Doing this when we also have updates to DM processing we would like to redo seems natural.  

We could imagine keeping a small set around to do some studies on the effects of these changes but I am particularly interested in the future to simulate things like sensor defects and test our defect finding and mask creation routines to check our sensitivity to masking. I believe this might require a lot of area.  I would be interested in hearing from @rmjarvis and @rhl about this for example.

So, I was wondering: if we can't keep the e-images on disk,  could we consider storing them to tape either at NERSC or ANL for the duration of the run 2 era?  If I *had* to choose one I might even suggest we only keep the amp files until we make the calexps since we can regenerate the amp files again quickly.

What do other people think?

**Comment by rmjarvis** [comment] 2018-08-28 22:02
I don't foresee any problem with not storing the e-images if that's required for storage concerns.  I agree that we would ideally store both, but it's not obvious that there is a big benefit to having e-images rather than images with gain and overscan and whatnot applied.  At least once we're confident that the readout chain stuff is being applied correctly.  (Which maybe we already are.)

**Comment by wmwv** [comment] 2018-08-30 12:39
Keeping only the amplifier files on disk and storing the e-image files on tape makes sense to me.

We expect that things are OK, but having the e-images on tape provides an easy fall-back plan if we want to regenerate amplifier images because we found some problem, or even just to regenerate a small subset to explore some effect.

**Comment by katrinheitmann** [comment] 2018-08-30 13:27
The problem is that if we have to write out all of them on disk + ckpt 
files while Run 2.0i is happening we will have up to 15M files and 600TB 
of data, and 400TB instead of 200TB in the end after the run is done. 
This is highly non-trivial to manage and to get this much storage is not 
easy. For the small subset to explore you could use Run 1.2i, no?

How worried are you that the amplifier files could have problems?

Also, Heather and Richard should chime in about our tape situation at 
NERSC.

**Comment by richardxdubois** [comment] 2018-08-30 14:54
Checking our HPSS balance, we only have 100 TB in the tape bank. This is partly because in the spring we ran out and had to ask for more; they tried to give us the minimum until the fall. Looks like we'll have to reopen that request/discussion.

And I see we have 800 TB free still in disk in projecta.

**Comment by cwwalter** [comment] 2018-08-30 15:11
What about making the production of the amp files part of the workflow (as opposed to doing it all in one step at the end).  Then, since the production will take a few weeks, you could immediately start staging the e-images to tape or to a staging area at NERSC etc as the run is going.  This way you wouldn't ever collect that large group of files at ANL.

**Comment by salmanhabib** [comment] 2018-08-30 15:37
On talking with Jim, it seems possible that (in ImSim) one can reconstruct the eimages from the amp files by noting the seeds used to generate the read noise and the dark noise signals. Apparently these are added linearly at the end of the processing, hence can be removed knowing the seed info; Jim is looking into this now.

**Comment by cwwalter** [comment] 2018-08-30 15:46
Oh, that would be nice. I had been thinking that the combination of x-talk + cti with noise meant information was lost. But since those are all linear matrix operations, I guess it could work. Currently we aren't applying non-linearity in the readout, which I guess might break this.

**Comment by jchiang87** [comment] 2018-08-30 15:50
As Salman noted, I checked and there are just two places (read noise and dark current) where random noise is added, and all of the operations for making these amp files are indeed linear, so this should be doable.

**Comment by wmwv** [comment] 2018-08-30 15:52
If we can reconstruct them, then I agree we don't need to keep the e-image files.

**Comment by rmjarvis** [comment] 2018-08-30 16:06
I think the only information loss would be in float -> int conversion, which I would have thought would happen at least once in this process.

**Comment by jchiang87** [comment] 2018-08-30 16:15
Yes, that float->int conversion does happen when the amp files are written out.

**Comment by wmwv** [comment] 2018-08-30 16:36
Yes, the full sense of my thought was, the main reason I might think we would want to keep these around was to regenerate different sensor effects.  As long as things are linear, we have a reasonable way of using the existing amplifier image to model a different sensor effect through these linear transformations.  It's true that we aren't guaranteed to get exactly the same thing as if we had taken the e-image files and applied that transformation, but if we are sensitive to things at the int->float->int->float->int level (I think I counted that right) in DC2 I will (a) mostly be shocked and surprised; but (b) we can definitely check off as demonstrated what ever analysis it was that we were trying to do.

**Comment by rmjarvis** [comment] 2018-08-30 18:19
>  if we are sensitive to things at the int->float->int->float->int level (I think I counted that right) in DC2 I will (a) mostly be shocked and surprised; 

FWIW, I would be shocked if that sequence doesn't screw up the sensor effects in important ways.

**Comment by salmanhabib** [comment] 2018-08-30 18:27
long ints or short ints?

**Comment by rmandelb** [comment] 2018-08-30 18:39
So it seems like going back from amp -> e-image isn't quite possible because of the quantization step involved in e-image -> amp, even though the other elements of the process are reversible?

It sounds to me like committing to store the e-images for all of Run 2.0 is a big expense that isn't fully justified.  We don't know that we definitely are going to want to make alternative variants of the steps from amps->e-images (as opposed to just being happy with Run 2.0 as-is, or as opposed to deciding our highest priority is to explore something that goes into the e-images, and hence requires a new simulation set entirely).  I can buy that we *might* want to do so, but I just don't see a strong science justification that Run 1.2i-scale areas would be insufficient for that purpose.  So if we're keeping e-images for Run 1.2i I would advocate for it to be the playground for such things, and then we don't have to store them even on tape for Run 2.0i.  Alternatively if there is such a concern that a large area could be needed for those test, what about storing the e-images for say 1-2 bands for Y1 of Run 1.2i? That would be 1/30-1/60 of the cost of storing e-images for Run 2.0i (1/3 or 1/6 factor from the bands, 1/10 from the Y10->Y1) and hence more comparable to the e-image cost for Run1.2i than Run 2.0i.

To be clear, in my mind the biggest reason to keep e-images would be if there was some concern in validating the steps in going from e-images to amps (so you want to have both around to check that), but by the time we get to Run 2.0i we should be past that.

Finally, I am looking forward to watching the Mike vs. Michael showdown.

**Comment by rmandelb** [comment] 2018-08-30 23:33
... Follow-up to my comments from 5 hours ago: @fjaviersanchez and @rmjarvis - do the planned validation tests for Run 1.2i include tests that the e-image -> amp steps are happening correctly?  It seems like those need to be a priority if we're not planning to keep e-images for Run 2.0i.

**Comment by rmjarvis** [comment] 2018-08-31 00:40
I'm not sure.  So far we're just testing the e-images, since that's all we have I think.  But we were going to run the same tests on the calexp images once we have them.  So I guess this tests that e-image -> amp image -> DM -> calexp image works correctly, which is probably most of what we care about.

The other set of tests that are relevant will be on the catalogs, which also indirectly test that the amp images are reasonable.

But I don't think we planned to do any tests directly on the amp images.  E.g. that it had the right cross talk or overscans or other such things.  I think we assumed that the round trip back in to calexps was sufficient. 

Did you want something explicitly testing features of the amp images?  Or are we ok to just implicitly test them via the calexps?

**Comment by rmandelb** [comment] 2018-08-31 01:15
I'm fine with implicit testing.

**Comment by cwwalter** [comment] 2018-08-31 17:58
Jim, Is the float->int truncation only in the last step when you write them out to the FITS file, and do you do it explicitly (as opposed to it being the intrinsic FITS representation)?

I don't typically like introducing such things as they can cause problems later when people forget about it, but would it be possible to store the amp fits HDUs as floats and have them be converted to int on read in?  That way perhaps we could indeed reproduce the e-image as suggested by you and Salman?

Aside from all the issues mentioned before with producing new amp files themselves, especially with the short checking time before 2.0i, there are certain classes of simulation errors we might be able to "fix up" without re-creating the eimage files if we run into problems later.

**Comment by wmwv** [comment] 2018-08-31 18:09
We don't want the fully-simulated amp files as floats.  We should match the expected structure for the actual images, which will be int.

We will gain much more from having things that are supposed to look exactly like the LSST camera images than from preserving the ability to exactly recreate a different sensor model from a fully-simulated amp file.

E.g., the recent overscan median vs. mean estimation (https://jira.lsstcorp.org/browse/DM-15203) issue.

I'd much rather deal with the subtleties of re-doing a sensor model yielding slight different things, than all of Run 2.0 yielding slightly different things.

**Comment by jchiang87** [comment] 2018-08-31 18:10
I was just typing the contrary opinion to Michael's, but having read his post, I agree with his conclusion.

**Comment by cwwalter** [comment] 2018-08-31 18:17
Right.. I agree with you (Michael), we always want to look just like the real camera and normally wouldn't suggest such a thing.

But, just to be clear I was asking a narrower technical question and wondering if we could easily arrange it so that it always looks exactly like our expected structure (as ints) on read-in but internally still have the float representation available.  Maybe we use enough tools and it is dangerous enough that it isn't a good idea but I was first just asking if that was really the only truncation int the process.

**Comment by jchiang87** [comment] 2018-08-31 18:28
I don't think there is a way to do this without modifying the Stack itself to do the conversion on read.  In any case, the conversion is done in imsim on the pixel data before writing the file.

**Comment by cwwalter** [comment] 2018-08-31 18:30
> I don't think there is a way to do this without modifying the Stack itself to do the conversion on read. In any case, the conversion is done in imsim on the pixel data before writing the file.

OK, I understand thanks.

**Comment by RobertLuptonTheGood** [comment] 2018-08-31 18:31
If it would help, we could make changes to allow reading a float as an int (although it's contrary to what @TallJimbo has just RFCd)

**Comment by salmanhabib** [comment] 2018-08-31 18:59
There are ways to skin this cat within ImSim but if 32bit int is ok as is, we may not have to do anything.

**Comment by cwwalter** [comment] 2018-08-31 21:51
BTW does the fits file understand we have 18 bits.  Or do we just restrict ourselves to them?

**Comment by sethdigel** [comment] 2018-09-01 00:38
The e-images max out at 100k electrons per pixel.  So the amplifier images should live within 18 bits too.

**Comment by wmwv** [comment] 2018-09-01 17:54
The encoding in the FITS file is as a signed 32-bit with a BZERO to translate to an unsigned range (this is a FITS convention dating to the historic lack of FORTRAN support for unsigned ints).

The actual recorded count values should be within the 18 bits.  (and in fact 17 bits for 100k electrons).

I understand the PhoSim files are generated with a gain=1.  But the ImSim files have a gain=1.7.

For a gain value of 1.7, then in fact the actual integer count values in the amplifier images should be within 16 bits.  (100k/1.7 ~ 59k).  This means we should be able to store the ImSim raw images in ADU as 16-bit ints.

As soon as we do anyting to those files, we'll start generating 32-bit floats files.

This ends up not directly addressing the e-image vs. amplifier file question; but suggest that we lose no information in storing the ImSim raws as 16-bit ints.

**Comment by jchiang87** [comment] 2018-09-01 17:58
For current raft-level testing, the gains are ~0.7, so imply pixel values up to ~140k.

**Comment by cwwalter** [comment] 2018-09-03 14:54
What do the REBs actually present to the DAQ? Is the conversion happening in the CCS?

**Comment by katrinheitmann** [comment] 2019-04-12 20:20
@cwwalter @jchiang87 Have we converged on this? If so, can we close the issue with a brief summary? Thanks!

**Comment by jchiang87** [comment] 2019-04-12 20:25
I think we have de facto converged on not writing the eimages, and I am inclined to continue this practice until we can demonstrate a real need to do so.  closing.

**Closed by jchiang87** 2019-04-12 20:25 UTC
Labels: Run 2.0, discussion
